# Automatically generated by Pynguin.
import state as module_0
import game_rules as module_1


def test_case_0():
    quit_0 = module_0.Quit()
    assert quit_0.state_id == 'ST_QUIT'
    bool_0 = None
    game_start_0 = module_0.GameStart()
    assert game_start_0.state_id == 'ST_GAME_START'
    set_0 = {bool_0, quit_0, game_start_0}
    str_0 = 'D>LQJxJh)=gkx'
    var_0 = quit_0.update(str_0)
    assert var_0 is None
    var_1 = quit_0.update(set_0)
    assert var_1 is None
    display_0 = module_0.Display()
    assert display_0.state_id == 'ST_GENERAL'
    display_1 = module_0.Display()
    assert display_1.state_id == 'ST_GENERAL'
    var_2 = display_1.update(display_0)
    assert var_2 is None
    str_1 = ')4XeaUbNl{ge~'
    state_0 = display_1.using(str_1)
    assert state_0.state_id == 'ST_GENERAL'
    float_0 = -727.0
    var_3 = quit_0.update(float_0)
    assert var_3 is None
    float_1 = 350.698
    perform_activity_0 = module_0.PerformActivity()
    assert perform_activity_0.state_id == 'ST_ACTIVITY'
    var_4 = perform_activity_0.transitionate(float_1)
    assert var_4.state_id == 'ST_TURN'
    assert var_4.re_rol == 3


def test_case_1():
    play_game_0 = module_0.PlayGame()
    assert play_game_0.state_id == 'ST_TURN'
    assert play_game_0.re_rol == 3


def test_case_2():
    play_game_0 = module_0.PlayGame()
    assert play_game_0.state_id == 'ST_TURN'
    assert play_game_0.re_rol == 3
    var_0 = play_game_0.handle_answer_rerol()


def test_case_3():
    display_0 = module_0.Display()
    assert display_0.state_id == 'ST_GENERAL'
    game_over_0 = None
    perform_activity_0 = module_0.PerformActivity()
    assert perform_activity_0.state_id == 'ST_ACTIVITY'
    var_0 = perform_activity_0.transitionate(game_over_0)
    assert var_0.state_id == 'ST_TURN'
    assert var_0.re_rol == 3
    game_rules_0 = module_1.GameRules()
    assert game_rules_0 is not None
    str_0 = '&%P;ACO_o0n+\x0cG*Fk'
    state_0 = display_0.message(str_0)
    assert state_0.state_id == 'ST_GENERAL'
    play_game_0 = module_0.PlayGame()
    assert play_game_0.state_id == 'ST_TURN'
    assert play_game_0.re_rol == 3
    game_over_1 = module_0.GameOver()
    assert game_over_1.state_id == 'ST_GAME_OVER'
    game_start_0 = module_0.GameStart()
    assert game_start_0.state_id == 'ST_GAME_START'
    var_1 = game_over_1.update(game_start_0)
    assert var_1 is None
    display_1 = module_0.Display()
    assert display_1.state_id == 'ST_GENERAL'
    str_1 = '\x0bhY]K_mH0g{6{'
    state_1 = display_0.message(str_1)
    assert state_1.state_id == 'ST_GENERAL'
    game_start_1 = module_0.GameStart()
    assert game_start_1.state_id == 'ST_GAME_START'


def test_case_4():
    display_0 = module_0.Display()
    assert display_0.state_id == 'ST_GENERAL'
    str_0 = display_0.get_message()
    assert str_0 == ''
