# Automatically generated by Pynguin.
import ui as module_0


def test_case_0():
    text_u_i_0 = module_0.TextUI()


def test_case_1():
    float_0 = -898.6
    text_u_i_0 = module_0.TextUI()
    var_0 = text_u_i_0.display(float_0)
