# Automatically generated by Pynguin.
import player as module_0


def test_case_0():
    try:
        player_0 = None
        str_0 = '+}lwbD='
        str_1 = 'zCUz,fdQlS$cnt`V#'
        character_0 = module_0.Character(str_0, str_1)
        assert character_0.name == '+}lwbD='
        assert character_0.description == 'zCUz,fdQlS$cnt`V#'
        var_0 = character_0.visit_character_stats_rules(player_0)
        doc_0 = module_0.Doc()
        assert var_0 is None
        assert doc_0.name == 'Doc Holyday'
        assert doc_0.description == "Cada vez que uses 3 o más disparos '1' y/o '2' tambièn recuperas 2 puntos de vida."
        var_1 = doc_0.initialize(player_0)
    except BaseException:
        pass
