# Automatically generated by Pynguin.
import game_rules as module_0
import player as module_1


def test_case_0():
    game_rules_0 = module_0.GameRules()


def test_case_1():
    player_0 = module_1.Player()
    bool_0 = True
    game_rules_0 = module_0.GameRules()
    bool_1 = game_rules_0.visit_throw_dice(player_0, bool_0)
    assert bool_1 is False
    assert player_0.name == ''
    assert player_0.life == 0
    assert player_0.arrows == 0
    assert player_0.dice_count == 6
    assert player_0.status == 'alive'
    assert player_0.character is None
    assert player_0.role is None
    assert game_rules_0 is not None
    assert module_1.Player.S_DEAD == 'dead'
    assert module_1.Player.S_ALIVE == 'alive'
    assert module_1.Player.S_GHOST == 'ghost'
