# Automatically generated by Pynguin.
import game_rules as module_0
import player as module_1


def test_case_0():
    game_rules_0 = module_0.GameRules()
    assert game_rules_0 is not None


def test_case_1():
    game_data_0 = None
    die_brave_0 = module_0.DieBrave(game_data_0)
    assert die_brave_0.value == ''
    var_0 = die_brave_0.execute()
    assert var_0 is None
    player_0 = module_1.Player()
    assert player_0.name == ''
    assert player_0.life == 0
    assert player_0.max_life == 0
    assert player_0.arrows == 0
    assert player_0.dice_count == 6
    assert player_0.status == 'alive'
    assert player_0.dice_value == ['', '', '', '', '', '']
    assert player_0.character is None
    assert player_0.role is None
    assert player_0.attack_vector == {'clockwise': [], 'backwards': []}
    assert module_1.Player.S_DEAD == 'dead'
    assert module_1.Player.S_ALIVE == 'alive'
    assert module_1.Player.S_GHOST == 'ghost'
