# Automatically generated by Pynguin.
import player as module_0


def test_case_0():
    try:
        elie_0 = module_0.Elie()
        assert elie_0.name == 'Moli Stark'
        assert elie_0.description == 'Cada vez que otro jugador deba perder 1 o más puntos de vida puedes perderlos en su lugar'
        player_0 = None
        var_0 = elie_0.initialize(player_0)
    except BaseException:
        pass
