# Automatically generated by Pynguin.
import ui as module_0
import pygame as module_1
import game_rules as module_2


def test_case_0():
    try:
        surface_0 = None
        graphical_u_i_0 = module_0.GraphicalUI(surface_0)
        assert graphical_u_i_0.surface is None
        assert graphical_u_i_0.dice_selection == 0
        dict_0 = {graphical_u_i_0: surface_0, surface_0: graphical_u_i_0}
        text_u_i_0 = module_0.TextUI()
        assert text_u_i_0 is not None
        var_0 = text_u_i_0.display(dict_0)
        assert var_0 is None
        surface_1 = module_1.Surface()
    except BaseException:
        pass


def test_case_1():
    try:
        surface_0 = None
        list_0 = []
        text_u_i_0 = module_0.TextUI(*list_0)
        var_0 = text_u_i_0.display(text_u_i_0)
        tuple_0 = surface_0,
        str_0 = '-x0oQO{\rBhz'
        str_1 = '\t5|Bk_v.}>FW'
        graphical_u_i_0 = module_0.GraphicalUI(surface_0)
        assert text_u_i_0 is not None
        assert var_0 is None
        assert graphical_u_i_0.surface is None
        assert graphical_u_i_0.dice_selection == 0
        var_1 = graphical_u_i_0.draw_box(str_0, str_1, tuple_0)
    except BaseException:
        pass


def test_case_2():
    try:
        surface_0 = None
        graphical_u_i_0 = module_0.GraphicalUI(surface_0)
        assert graphical_u_i_0.surface is None
        assert graphical_u_i_0.dice_selection == 0
        list_0 = []
        u_i_0 = module_0.UI(*list_0)
        assert u_i_0 is not None
        game_data_0 = module_2.GameData()
        assert game_data_0.keys is None
        assert game_data_0.arrows_left == 5
        var_0 = graphical_u_i_0.draw_status(game_data_0)
    except BaseException:
        pass


def test_case_3():
    try:
        surface_0 = None
        list_0 = []
        text_u_i_0 = module_0.TextUI(*list_0)
        graphical_u_i_0 = module_0.GraphicalUI(surface_0)
        assert text_u_i_0 is not None
        assert graphical_u_i_0.surface is None
        assert graphical_u_i_0.dice_selection == 0
        var_0 = text_u_i_0.display(text_u_i_0)
        assert var_0 is None
        str_0 = "'_/c"
        var_1 = graphical_u_i_0.display(str_0)
    except BaseException:
        pass


def test_case_4():
    try:
        surface_0 = None
        graphical_u_i_0 = module_0.GraphicalUI(surface_0)
        assert graphical_u_i_0.surface is None
        assert graphical_u_i_0.dice_selection == 0
        list_0 = []
        u_i_0 = module_0.UI(*list_0)
        assert u_i_0 is not None
        surface_1 = None
        tuple_0 = surface_1,
        tuple_1 = graphical_u_i_0.sum_vectors(tuple_0, tuple_0)
    except BaseException:
        pass
