# Automatically generated by Pynguin.
import ui as module_0


def test_case_0():
    text_u_i_0 = module_0.TextUI()


def test_case_1():
    surface_0 = None
    graphical_u_i_0 = module_0.GraphicalUI(surface_0)
    assert graphical_u_i_0.surface is None
